name: ServerCinematics
main: optic_fusion1.servercinematics.ServerCinematicsPlugin
version: ${project.version}
api-version: 1.13
description: Acts as a server-side replacement for Camera Studio Mod.
author: CosmoConsole
authors: [Optic_Fusion1, Kisko, Pietu1998]
contributors: [2008Choco]
commands:
   camera:
      aliases: [cam]
      description: Use ServerCinematics features.
      usage: /<command>
permissions:
   servercinematics.*:
      description: Gives access to all ServerCinematics features except servercinematics.cmd.
      default: op
      children:
         servercinematics.use: true
         servercinematics.play: true
         servercinematics.edit: true
         servercinematics.fplay: true
   servercinematics.use:
      description: Gives access to all ServerCinematics features except servercinematics.cmd.
      default: op
      children:
         servercinematics.play: true
         servercinematics.edit: true
         servercinematics.fplay: true
   servercinematics.play:
      description: Allows playing paths.
      default: op
   servercinematics.edit:
      description: Allows editing paths.
      default: op
   servercinematics.fplay:
      description: Allows playing paths for other people.
      default: op
   servercinematics.cmd:
      description: Allows setting path commands. Not granted by default because of the security implications.
      default: false

